version: 2

models:
  - name: squ_python_model

    # Document within the same codebase
    description: My transformation written in Python

    # Configure in ways that feel intuitive and familiar
    config:
      query: SecurityIncident
      tags: ['api']