name: Deploy to GitHub Pages and build

permissions:
  contents: read
  pages: write

on: ["workflow_dispatch", "push"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: block
        allowed-endpoints: >
          download.pytorch.org:443
          files.pythonhosted.org:443
          github.com:443
          objects.githubusercontent.com:443
          pypi.org:443
          quarto.org:443
          registry.npmjs.org:443
          www.quarto.org:443


    - name: Upload to pages branch
      uses: fastai/workflows/quarto-ghp@6f01ea106ba2b565c66ad88a826bdbc4d7e378c9 # master
      with:
        version: '3.11' 
    - name: build
      run: ./build.sh
