name: Deploy to GitHub Pages and build release if tagged

permissions:
  contents: write
  pages: write

on: ["workflow_dispatch", "push"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - name: Upload to pages branch
      uses: fastai/workflows/quarto-ghp@6f01ea106ba2b565c66ad88a826bdbc4d7e378c9 # master
      with:
        version: '3.11' 
    - name: build
      run: ./build.sh
    - name: release upload
      uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 # v2.0.4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*