name: Deploy to GitHub Pages and build release if tagged

permissions:
  contents: write
  pages: write

on: ["workflow_dispatch", "push"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Upload to pages branch
      uses: fastai/workflows/quarto-ghp@master
      with:
        version: '3.11' 
    - name: build
      run: ./build.sh
    - name: release upload
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*